# Generated by Django 4.0.4 on 2022-04-20 12:00

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(blank=True, max_length=5000, null=True, verbose_name='Long description'),
        ),
    ]
