# Generated by Django 4.0.4 on 2022-04-24 16:47

import tinymce.models
from django.db import migrations, models


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    places = apps.get_model("places", "Place")

    for place in places.objects.all():

        if place.description_short is None:
            place.description_short = ""

        if place.description_long is None:
            place.description_long = ""

        place.save()


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0004_alter_place_description_long"),
    ]

    operations = [
        migrations.RunPython(combine_names),
        migrations.AlterField(
            model_name="place",
            name="description_short",
            field=models.TextField(
                max_length=500,
                verbose_name="Short description",
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="description_long",
            field=tinymce.models.HTMLField(
                max_length=5000,
                verbose_name="Long description",
            ),
        ),
    ]
